### ISSUE TITLE
GLIBC dependency

### ISSUE THREAD

**Issue by slw287r** [niu-lab/msisensor-blood#1]
Hi gurus of niu-lab,

Thanks for your excellent msisensor-series. I failed to paddle the ctDNA version of msisensor with unmet GLIBC requirements.

```
./msisensor-ct: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./msisensor-ct)
```

Would you be kind to provide a static version with GLIBC before version 2.23?
BTW, we can handle msisensor2 with GLIBC_2.22.

Regards,
Richard

**Comment by owehann** [comment]
Sorry, Richard.
Due to the requirements of a particular algorithm library, we are unable to provide MSIsensor-ct that relies only on the lower GLIBC version. However, this problem can be solved by working with new environment variables, or only with the environment configuration on which the new MSIsensor-ct depends. You can download the latest zlib version at http://www.zlib.net/ to resolve the issue.
Thanks 
Xinyin

**Comment by slw287r** [comment]
> Sorry, Richard.
> Due to the requirements of a particular algorithm library, we are unable to provide MSIsensor-ct that relies only on the lower GLIBC version. However, this problem can be solved by working with new environment variables, or only with the environment configuration on which the new MSIsensor-ct depends. You can download the latest zlib version at http://www.zlib.net/ to resolve the issue.
> Thanks
> Xinyin

Hi, Xinyin

I have the latest zlib available (1.2.11) installed. The dependency issue is actually related to the math library (`libm.so`) which in turn requires the higher glibc.

Any way, I managed to make msisensor-ct run by encapsulating it into a CentOS 8 docker along with a local version libgomp.so which msisensor-ct complains. But it's not as convenient as a standalone version.

@Beifang, Please consider building a static version under CentOS 6 if that is possible.

Thanks again,
Richard

**Comment by zhangyafeng1** [comment]
> Hi gurus of niu-lab,
> 
> Thanks for your excellent msisensor-series. I failed to paddle the ctDNA version of msisensor with unmet GLIBC requirements.
> 
> ```
> ./msisensor-ct: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./msisensor-ct)
> ```
> 
> Would you be kind to provide a static version with GLIBC before version 2.23?
> BTW, we can handle msisensor2 with GLIBC_2.22.
> 
> Regards,
> Richard

Hi,Richard:
I encountered the same error as you before, I updated the GCC can be resolved.
`wget ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.gz`

**Comment by shenweiyan** [comment]
> Sorry, Richard. Due to the requirements of a particular algorithm library, we are unable to provide MSIsensor-ct that relies only on the lower GLIBC version. However, this problem can be solved by working with new environment variables, or only with the environment configuration on which the new MSIsensor-ct depends. You can download the latest zlib version at http://www.zlib.net/ to resolve the issue. Thanks Xinyin

I got the same error on my CentOS 6.5 Server. The highest version of my glibc is 2.15, as the upgrade of GLIBC_2.23 is more complicated, is there any other solution? Thank you.
