### ISSUE TITLE
trouble with GLIBC version

### ISSUE THREAD

**Issue by Zho-o-o-u** [niu-lab/msisensor-blood#5]
Hi Xinyin,
I want to test this software for making pipeline, but i have trouble with GLIBC version.  the version of gcc and glibc in our server are not suitable, would you be kind to provide  a docker image of environment dependency? Thank you !

Best wish
zhou

**Comment by owehann** [comment]
Hi Zhou，
If in a rush, this can be easily solved by working with new environment variables, or only with the environment configuration on which the new MSIsensor-ct depends. The latest zlib version is available at http://www.zlib.net/ to resolve the issue. We will take your docker suggestion into full consideration, but it may take some time.
Thanks
Xinyin

**Comment by Zho-o-o-u** [comment]
Thanks a lot . I will try to solve this rush.
