### ISSUE TITLE
how design a customized panel with more than 30 of 1476 sites accordingly?

### ISSUE THREAD

**Issue by biofer** [niu-lab/msisensor-blood#6]
Dear author,

For the sentence ‘Furthermore, its robustness renders MSIsensor-ct compatible with any pan-cancer sequencing panels covering more than 30 out of 1476 classifiers.’ in the introduction part of the paper ‘MSIsensor-ct: microsatellite instability detection using cfDNA sequencing data’, I wonder how design a customized panel with more than 30 of 1476 sites accordingly. Can you give me some help? I will be appreciated for your reply, thank you very much! 

Thank you very much for your work！

**Comment by Beifang** [comment]
Thanks for your interest on msisensor-ct. It a relatively complicated trainning process, so we have not released the code of trainning pipeline. You can send me email, once you have quite a number of samples in hand.

**Comment by biofer** [comment]
Thank you for your reply! Now we are accumulating clinical samples and designing the customized panel at this stage. So we are confused if our panel can contain more than 30 of 1476 sites. It is hard to adjust after customization. 
I'm going to run the WES data with MSIsensor-ct, and then select 30+MS loci from the result file “*.output_dis”. Are these selected 30+MS loci included in 1476 sites? Is this strategy practicable?

**Comment by Beifang** [comment]
yeah. practicable .

**Comment by biofer** [comment]
I really appreciate your help.
